# -*- coding: utf-8 -*-
"""Customer Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cthNFTmM5u24XZROUCPnnATh47Wzpx-h
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install gower

!pip install -U plotly

#!pip install -U kaleido

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gower
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import plotly.express as px

mall_data = pd.read_csv("/content/drive/MyDrive/DATASETS/Mall_Customers.csv")
print(mall_data.columns.to_list())
mall_data.head(10)

mall_data = mall_data.rename(columns = {
    'CustomerID' : 'customer_id',
    'Gender' : 'gender',
    'Age' : 'age',
    'Annual Income (k$)' : 'annual_income',
    'Spending Score (1-100)' : 'spending_score'

})



mall_data.info()

# Density Plots

fig, axes = plt.subplots(1 ,3 , figsize=(18,5))

sns.histplot(
    data = mall_data,
    x = 'age',
    kde = True,
    bins = 10,
    ax = axes[0]
)
axes[0].set_title('Histogram of Age')
axes[0].set_xlabel('Age')

sns.histplot(
    data = mall_data,
    x = 'annual_income',
    kde = True,
    bins = 10,
    ax = axes[1]
)
axes[1].set_title('Histogram of Annual Income')
axes[1].set_xlabel('Annual Income')

sns.histplot(
    data = mall_data,
    x = 'spending_score',
    kde = True,
    bins = 10,
    ax = axes[2]
)
axes[2].set_title('Histogram of Spending Score')
axes[2].set_xlabel('Spending core')

plt.tight_layout()
plt.show()

# Scatter Plots

import matplotlib.pyplot as plt
import seaborn as sns

palette = {'Male': 'blue', 'Female': 'red'}

fig, axes = plt.subplots(1, 3, figsize=(18, 5))


sns.scatterplot(
    data=mall_data,
    x='age',
    y='annual_income',
    hue='gender',
    palette=palette,
    ax=axes[0]
)
axes[0].set_title('Age vs Annual Income')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Annual Income')

sns.scatterplot(
    data=mall_data,
    x='age',
    y='spending_score',
    hue='gender',
    palette=palette,
    ax=axes[1]
)
axes[1].set_title('Age vs Spending Score')
axes[1].set_xlabel('Age')
axes[1].set_ylabel('Spending Score')


sns.scatterplot(
    data=mall_data,
    x='annual_income',
    y='spending_score',
    hue='gender',
    palette=palette,
    ax=axes[2]
)
axes[2].set_title('Annual Income vs Spending Score')
axes[2].set_xlabel('Annual Income')
axes[2].set_ylabel('Spending Score')

plt.tight_layout()
plt.show()

mall_data = pd.read_csv("/content/drive/MyDrive/DATASETS/Mall_Customers.csv")

mall_data = mall_data.rename(columns={
    'CustomerID': 'customer_id',
    'Gender': 'gender',
    'Age' : 'age',
    'Annual Income (k$)': 'annual_income',
    'Spending Score (1-100)':'spending_score'
})


X = mall_data.drop(
    columns = ['customer_id'],
    axis = 1
)

# Gower Distance
from scipy.spatial.distance import squareform
from scipy.cluster.hierarchy import linkage, dendrogram

gower_dist = gower.gower_matrix(X)

gower_condensed = squareform(gower_dist)

Z = linkage(gower_condensed, method='average')

plt.figure(figsize=(10, 6))
dendrogram(Z, labels=mall_data.index, leaf_rotation=90)
plt.title('Hierarchical Clustering Dendrogram')
plt.ylabel('Gower Distance')

plt.savefig("/content/drive/MyDrive/DATASETS/dendogram.png", dpi=300, bbox_inches="tight")
plt.show()

# Hierarchical Clustering Results
clusters = fcluster(Z, 2, criterion='maxclust')
mall_data['cluster'] = clusters


palette = 'Set1'


fig, axes = plt.subplots(1, 3, figsize=(18, 5))


sns.scatterplot(
    data=mall_data,
    x='age',
    y='annual_income',
    hue='cluster',
    palette=palette,
    ax=axes[0]
)
axes[0].set_title('Age vs Annual Income')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Annual Income')


sns.scatterplot(
    data=mall_data,
    x='age',
    y='spending_score',
    hue='cluster',
    palette=palette,
    ax=axes[1]
)
axes[1].set_title('Spending vs Annual Income')
axes[1].set_xlabel('Spending Score')
axes[1].set_ylabel('Annual Income')


sns.scatterplot(
    data=mall_data,
    x='annual_income',
    y='spending_score',
    hue='cluster',
    palette=palette,
    ax=axes[2]
)
axes[2].set_title('Age vs Spending Score')
axes[2].set_xlabel('Age')
axes[2].set_ylabel('Spending Score')

plt.tight_layout()
plt.show()

"""# K Means"""

mall_data = pd.read_csv("/content/drive/MyDrive/DATASETS/Mall_Customers.csv")

mall_data = mall_data.rename(columns={
    'CustomerID': 'customer_id',
    'Gender': 'gender',
    'Age' : 'age',
    'Annual Income (k$)': 'annual_income',
    'Spending Score (1-100)':'spending_score'
})

X = mall_data[['annual_income' , 'age' , 'spending_score']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertia = []
K = range(1, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=0)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)


plt.figure(figsize=(8,5))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Number of clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal k')
plt.show()


k = 5
kmeans = KMeans(n_clusters = k, random_state = 0)
mall_data['cluster'] = kmeans.fit_predict(X_scaled)
cluster_map = {
    0: 1,
    1: 2,
    2: 3,
    3: 4,
    4: 5
}
mall_data['cluster'] = mall_data['cluster'].map(cluster_map)

plt.savefig("/content/drive/MyDrive/DATASETS/elbow.png", dpi=300, bbox_inches="tight")
plt.show()

palette = [
    '#440154',  # dark purple
    '#3B528B',  # blue-purple
    '#21908C',  # teal
    '#5DC863',  # green
    '#FDE725'   # yellow
]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))  # 1 row, 3 columns


sns.scatterplot(
    data = mall_data,
    x = 'age',
    y = 'annual_income',
    hue = 'cluster',
    palette = palette,
    ax = axes[0]
)
axes[0].set_title('Age vs Annual Income')


sns.scatterplot(
    data=mall_data,
    x='age',
    y='spending_score',
    hue='cluster',
    palette=palette,
    ax=axes[1]
)
axes[1].set_title('Age vs Spending Score')


sns.scatterplot(
    data=mall_data,
    x='annual_income',
    y='spending_score',
    hue='cluster',
    palette=palette,
    ax=axes[2]
)
axes[2].set_title('Annual Income vs Spending Score')

plt.tight_layout()
plt.show()

# 3-D Plot of Clusters
fig = px.scatter_3d(
    mall_data,
    x='age',
    y='annual_income',
    z='spending_score',
    color='cluster',
    color_continuous_scale='Viridis',
    symbol='cluster',
    hover_data=['age', 'annual_income', 'spending_score']
)

# Make the points smaller
fig.update_traces(marker=dict(size=2.5))  # default is usually ~6

fig.update_layout(
    title='Interactive 3D Scatterplot of Clusters',
    scene=dict(
        xaxis_title='Age',
        yaxis_title='Annual Income',
        zaxis_title='Spending Score'
    )
)

fig.show()

centroids_scaled = kmeans.cluster_centers_

# Convert back to original units
centroids_original = scaler.inverse_transform(centroids_scaled)

centroids_df = pd.DataFrame(
    centroids_original,
    columns=['annual_income', 'age', 'spending_score']
)

centroids_df.index = [1, 2, 3, 4, 5]
centroids_df.index.name = 'Cluster'
centroids_df = centroids_df[['age', 'spending_score', 'annual_income']]


print(centroids_df)

"""

-   Average Shopper – Offer general promotions and loyalty programs to ensure customer retention and consistent shopping
- Wealthy but Reserved – Emphasize premium-quality stores and personalized
experiences, including upscale restaurant deals and exclusive promotions, rather than frequent sales.
- Luxury Spenders – Offer more aggressive marketing for high-end items, including premium brand promotions , designer fashion brands , upscale restaurants, and premium jewelry to maximize engagement and sales.
- Frugal by Necessity – Target this group with more aggressive discounts and value bundles to get large amounts of items for a discounted price.
- Young, Impulsive Spenders – Collaborate with social media term to run promotions online to spread awareness and increase sales, focusing on trendy items following



"""

Average Shopper – Offer general promotions and loyalty programs to ensure customer
retention and consistent shopping


# Young Low-Spender (age = 39.87, spending = 19.36, income = 86.10) – Young, low spending, high income. Focus on premium experiences and exclusive offers rather than frequent discounts.

# Young High-Spender (age = 32.88, spending = 81.53, income = 86.10) – Young, very high spending, high income. Promote trendy items, online campaigns, and high-value products.

# Budget-Conscious Youth (age = 46.25, spending = 18.35, income = 26.75) – Young adults, low spending, low income. Use aggressive discounts, value bundles, and promotions for affordable products.

# Older Moderate-Spender (age = 25.19, spending = 62.24, income = 41.09) – Younger-middle age, moderate-high spending, moderate income. Offer convenience-focused deals, seasonal promotions, and mid-range product bundles.